apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgre-database-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-pv-1
    spec:
      containers:
      - name: postgre-container-1
        image: postgres:10.5
        ports:
        - containerPort: 9001
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgre-c-1
        - mountPath: "/etc/localtime"
          name: host-time
      volumes:
        - name: postgre-c-1
          hostPath: 
            path: /home/data/postgre-database-1
        - name: host-time
          hostPath:
            path: /etc/localtime

---

apiVersion: v1
kind: Service
metadata:
  name: postgre-service-1
  labels:
    app: postgres-pv-1
spec:
  type: NodePort
  ports:
  - name: postgre-port-1
    protocol: "TCP"
    port: 9001
    nodePort: 20001
    targetPort: 9001
  selector:
    app: postgres-pv-1
